### ISSUE TITLE
Dataset: Find missing header names

### ISSUE THREAD

**Issue by Huntler** [Huntler/ADBU#2]
Currently, not all files are read into the pandas data frame, because some headers are still missing. We do not know, what a column describes: fix is needed.

**Comment by AliHaider20** [comment]
I understood the bug but can you share an actual snip of the result?

**Comment by Huntler** [comment]
which result? Files without a header are not read and therefore missing in our pandas data frame. To solve this issue, we have to find the headers of each .txt file and add them to our pandas_importer.py (in line 10 and following)
